name: "emotion"
seed: 42
model:
  from_pretrained: "bert-base-uncased"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 2
  freeze_transformer_layers: "none"
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 5
  output_path: "./outputs/"

data:
  name: "tweet_eval/emotion"
  batch_size: 32
  label_column: "label"



