name: "emotion"
seed: 42
model:
  from_pretrained: "finiteautomata/bertweet-base-sentiment-analysis"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 2
  freeze_transformer_layers: "none"
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 5
  output_path: "./outputs/"
  contrastive:
    contrastive_loss_ratio: 1
    temperature: 0.07
    base_temperature: 0.07
    contrast_mode: "all"
  L2_normalize_encoded_feature: False

data:
  name: "tweet_eval"
  config: "emotion"
  batch_size: 32
  label_column: "label"
  subset: 0.1




