data:
  batch_size: 32
  label_column: label
  name: ./event_extractor/custom_datasets/TRECIS_event_type.py
model:
  L2_normalize_logits: false
  dropout_rate: 0.5
  epochs: 10
  freeze_transformer_layers: none
  from_pretrained: vinai/bertweet-base
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 1.0e-05
  num_transformer_layers: 2
  output_path: ./outputs/
name: trec_is_event_type
seed: 42
