data:
  batch_size: 32
  include_oos: false
  label_column: label
  name: ./event_extractor/custom_datasets/sexism_level_three.py
  validation: true
early_stopping:
  delta: 0
  tolerance: 15
model:
  L2_normalize_encoded_feature: false
  dropout_rate: 0.5
  epochs: 50
  freeze_transformer_layers: none
  from_pretrained: roberta-base
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 1.0e-05
  num_transformer_layers: full
  output_path: ./outputs/sexism/level_three/sl/
name: sexism_level_three_sl
seed:
- 0
- 1
- 2
visualizer:
- tsne
