data:
  batch_size: 32
  config: sentiment
  label_column: label
  name: tweet_eval
  validation: true
early_stopping:
  delta: 0
  tolerance: 5
model:
  L2_normalize_encoded_feature: false
  dropout_rate: 0.5
  epochs: 50
  freeze_transformer_layers: none
  from_pretrained: roberta-base
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 1.0e-05
  num_transformer_layers: full
  output_path: ./outputs/tweeteval/
name: sentiment_sl
seed: 2
