name: "sentiment_sl"
seed: 42
model:
  from_pretrained: "roberta-base"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: "full"
  freeze_transformer_layers: "none"
  learning_rate: 0.00001
  dropout_rate: 0.5
  epochs: 50
  output_path: "./outputs/"
  L2_normalize_encoded_feature: True

data:
  name: "tweet_eval"
  config: "sentiment"
  batch_size: 32
  label_column: "label"
  validation: True

early_stopping:
  tolerance: 20
  delta: 0



