from event_extractor.models.SequenceClassificationBase import SequenceClassification
from event_extractor.models.SingleLabelSequenceClassification import SingleLabelSequenceClassification, SingleLabelContrastiveSequenceClassification
from event_extractor.models.PrototypicalNetworks import PrototypicalNetworks
from event_extractor.models.MultiLabelSequenceClassification import MultiLabelSequenceClassification, MultiLabelContrastiveSequenceClassification

