augmenter:
  name: dropout
  num_samples: 2
data:
  batch_size: 32
  config: sentiment
  gradient_accu_step: 1
  include_oos: false
  label_column: label
  name: tweet_eval
  validation: true
early_stopping:
  delta: 0
  tolerance: 5
model:
  L2_normalize_encoded_feature: false
  L2_normalize_logits: false
  dropout_rate: 0.5
  epochs: 100
  freeze_transformer_layers: none
  from_pretrained: roberta-base
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 1.0e-05
  load_ckpt: ./outputs/tweeteval/experiments/scl/mlp_dropout/05/sentiment/seed_0/pretrained_models/sentiment_best_model.pt
  num_transformer_layers: full
  output_path: ./outputs/tweeteval/experiments/cohort2/roberta_base/
name: sentiment
seed:
- 0
- 1
- 2
visualizer:
- tsne
