data:
  batch_size: 16
  classes:
  - anger
  - anticipation
  - disgust
  - fear
  - joy
  - love
  - optimism
  - pessimism
  - sadness
  - surprise
  - trust
  config: subtask5.english
  label_column: label
  name: sem_eval_2018_task_1
  text_column: Tweet
  validation: true
early_stopping:
  delta: 0
  tolerance: 5
model:
  L2_normalize_encoded_feature: false
  contrastive:
    base_temperature: 0.3
    contrast_mode: all
    contrastive_loss_ratio: 0
    temperature: 0.3
  dropout_rate: 0.5
  epochs: 50
  freeze_transformer_layers: none
  from_pretrained: vinai/bertweet-base
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 0.0001
  num_transformer_layers: full
  output_path: ./outputs/semeval18/sl/
  type: multi-label
name: bertweet
seed:
- 0
- 1
- 2
