data:
  batch_size: 32
  config: subtask5.english
  label_column: label
  text_column: Tweet
  name: sem_eval_2018_task_1
  validation: true
  classes: [anger, anticipation, disgust, fear, joy, love, optimism, pessimism, sadness, surprise, trust]
early_stopping:
  delta: 0
  tolerance: 5
model:
  type: multi-label
  L2_normalize_encoded_feature: false
  contrastive:
    base_temperature: 0.3
    contrast_mode: all
    contrastive_loss_ratio: 0
    temperature: 0.3
  dropout_rate: 0.5
  epochs: 50
  freeze_transformer_layers: none
  from_pretrained: roberta-base
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 1.0e-04
  num_transformer_layers: 1
  output_path: ./outputs/semeval18/sl/
name: roberta
seed:
- 0