name: "banking77_many_shot_cohort_1"
model:
  from_pretrained: "bert-base-cased"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 1
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 10
data:
  name: "banking77"
  batch_size: 32
episode:
  n_way: 5
  k_shot: 3
  iteration: 20


