name: "trec_is_many_shot_cohort_1"
model:
  from_pretrained: "bert-base-cased"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 2
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 10
data:
  training_data_path: "../../data/trec_is/train.csv"
  testing_data_path: "../../data/trec_is/test.csv"
  label_column: "label"
  sentence_column: "sentence"
  batch_size: 16


