name: "trec_is_many_shot_cohort_1"
model:
  from_pretrained: "bert-base-cased"
  layers:
    layer1:
      n_in: 768
      n_out: 128
    layer2:
      n_in: 128
      n_out: 20
  n_layers: 1
  learning_rate: 0.001
  dropout_rate: 0.1
data:
  training_data_path: "../../data/trec_is/train.csv"
  testing_data_path: "../../data/trec_is/test.csv"

