name: "trec_many_shot_cohort_1"
seed: 42
model:
  from_pretrained: "bert-base-cased"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 1
  freeze_transformer_layers: "none"
  learning_rate: 0.0001
  dropout_rate: 0.2
  epochs: 20
  output_path: "./outputs/"

data:
  name: "trec"
  batch_size: 32
  label_column: "label-coarse"


