name: "trec_is_many_shot_cohort_1"
model:
  from_pretrained: "bert-base-cased"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 2
  freeze_transformer_layers: "none"
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 10
data:
  name: "./custom_datasets/TRECIS.py"
  batch_size: 32
  label_column: "label"



