name: "trec_is_event_type_few_shot"
seed: 42
model:
  from_pretrained: "vinai/bertweet-base"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 2
  freeze_transformer_layers: "none"
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 2
  output_path: "./outputs/"

data:
  name: "./custom_datasets/TRECIS_event_type.py"
  batch_size: null
  label_column: "label"
  subset: 0.01

episode:
  n_way: 3
  k_shot: 2
  iteration: 10
  n_query: 2
  replacement: True



