name: "trec_is_few_shot_cohort_1"
seed: 42
model:
  from_pretrained: "bert-base-cased"
  layers:
    layer1:
      n_in: 768
      n_out: 20
  num_transformer_layers: 1
  freeze_transformer_layers: "none"
  learning_rate: 0.0001
  dropout_rate: 0.5
  epochs: 5
  output_path: "./outputs/"

data:
  name: "./custom_datasets/TRECIS.py"
  batch_size: null
  label_column: "label"

episode:
  n_way: 3
  k_shot: 2
  iteration: 10
  n_query: 2
  replacement: True

