data:
  batch_size: 32
  label_column: label
  name: banking77
  subset: 0.1
model:
  L2_normalize_logits: false
  dropout_rate: 0.5
  epochs: 2
  freeze_transformer_layers: none
  from_pretrained: bert-base-cased
  layers:
    layer1:
      n_in: 768
      n_out: 20
  learning_rate: 1.0e-05
  num_transformer_layers: 1
  output_path: ./outputs/
name: banking77_many_shot_cohort_1
seed: 42
